name: Deploy Bitstrat Frontend Application to dockerhub

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version (example: v1.0.0)'
        required: true
        type: string

env:
  PROJECT: bitstrat
  IMAGE_NAME: xuehuiz/bitstrat-font

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ 设置短 SHA
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV
      - name: Set VERSION
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      # 3️⃣ 安装 Node.js
      - name: Setup Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
#          cache: 'npm'

      # 4️⃣ 安装依赖
      - name: Install dependencies
        run: npm install

      # 5️⃣ 打包生产
      - name: Build frontend (prod)
        run: |
          node --max-old-space-size=4096 node_modules/.bin/vite build
          npm run build:prod
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      # 6️⃣ 登录 Harbor
      - name: Login Harbor
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7️⃣ 构建并推送 Docker 镜像
      - name: Build & Push Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:$VERSION \
            -t $IMAGE_NAME:latest \
            .
          docker push \
            $IMAGE_NAME:$VERSION

          docker push \
            $IMAGE_NAME:latest

      # 8️⃣ 通知服务器 / Helm 更新（可选）
#      - name: Notify server to update
#        run: |
#          curl -k -X POST \
#          "你的webhook地址?tag=${SHORT_SHA}"
